#  ARQUIVO: tp02_breakout.pde
#  EQUIPE:
#          Lucas Samuel Vieira - 24072
#  DATA:
#          03/04/2015
#  VERSÃO:
#          0.1 beta
#  DESCRIÇÃO:
#          Makefile para execução e compilação de sketches do Processing
#          via linha de comando (Linux).

.PHONY: build
all: build

build:
	processing-java --sketch=../tp04_nagai --output=./bin --export --force --no-java
