enum WeatherField
{
	CITY,
	REGION,
	COUNTRY,
	LAST_UPDATED,
	LONGITUDE,
	LATITUDE,
	WIND_TEMPERATURE,
	WIND_SPEED,
	WIND_DIRECTION,
	HUMIDITY,
	VISIBILITY,
	PRESSURE,
	RISING,
	SUNRISE,
	SUNSET,
	TEMPERATURE,
	CONDITION,
	TEMPERATURE_LOW_TOMORROW,
	TEMPERATURE_HIGH_TOMORROW
	// There ARE more, but I don't feel I'll even be using
	// these ones this much...
};